info:
  contact: {}
  license: {}
paths:
  /check:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: type
        in: formData
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"result":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登陆验证接口
swagger: "2.0"
